### ISSUE TITLE
Support for GPU Information

### ISSUE THREAD

**Issue by chrisreedio** [ProtozeFOSS/KrakenZPlayground#4]
First, Thanks so much for making this! It has been needed for so long! 

The stock NZXT software has the dual infographic that includes GPU temperature. 

I have tried a few examples on my Z73 with good success so far. But really enjoyed having both CPU temp and GPU temp on my display. 

Is the GPU temperature exposed anywhere in the software for the QML 'templates'?

**Comment by Tpimp** [comment]
Not yet. I got permission to use the implementation used in openRGB but it won't likely land until version 1.2 but I will get to it.

**Comment by stuu3k** [comment]
I would also like this, but I have one additional feature to add to it please, the stock NZXT app only shows you the Temperature of the First GPU, if you have 2 GPU's there is no way of selecting which GPU to show.

It would be really nice if we could enter GPU0 \ GPU1 etc so that we can get it to show the correct GPU Temperature or maybe even both if you so wanted.

Thanks

**Comment by Tpimp** [comment]
Got it! Should be working in v1.2 release.

**Comment by stuu3k** [comment]
Great news thanks very much. :)
